location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/octomap.git
    name: octomap
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/octomap
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/OctoMap/octomap_rviz_plugins
    name: octomap_rviz_plugins
    rev: kinetic-devel
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/octomap_rviz_plugins
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/OctoMap/octomap_msgs
    name: octomap_msgs
    rev: melodic-devel
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/octomap_msgs
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/octomap_tools.git
    name: octomap_tools
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/octomap_tools
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_octomap_server.git
    name: mrs_octomap_server
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_octomap_server
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_octomap_planner.git
    name: mrs_octomap_planner
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_octomap_planner
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/OctoMap/octomap_ros
    name: octomap_ros
    rev: melodic-devel
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/octomap_ros
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - repo: https://github.com/ctu-mrs/octomap.git
    name: octomap
    rev: 4c9fcd313accf3f5b270eb1c17f4e24829dd2a24
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/octomap
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/octomap_tools.git
    name: octomap_tools
    rev: a902bb5fe1176406c05981c32464e7647f1a4384
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/octomap_tools
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_octomap_server.git
    name: mrs_octomap_server
    rev: ef87cddd6e14a32801d022c72e23dee80cd7d0d7
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_octomap_server
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_octomap_planner.git
    name: mrs_octomap_planner
    rev: 19217d04b74636d1258d5e09440e99fcf4e71e70
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_octomap_planner
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/OctoMap/octomap_ros
    name: octomap_ros
    rev: fb462a9e542dad60b6287b5e610c24b998bb65aa
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/octomap_ros
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/OctoMap/octomap_rviz_plugins
    name: octomap_rviz_plugins
    rev: c766489f62a96a4d37b3fa97d1aa867a0b81cf1c
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/octomap_rviz_plugins
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/OctoMap/octomap_msgs
    name: octomap_msgs
    rev: dcaaf62bd071db0fcd806a98a9101a2e470f7f6d
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/octomap_msgs
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
