location: .gitman
sources:
  - repo: https://github.com/OctoMap/octomap
    name: octomap
    rev: devel
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/octomap
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/OctoMap/octomap_rviz_plugins
    name: octomap_rviz_plugins
    rev: kinetic-devel
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/octomap_rviz_plugins
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/OctoMap/octomap_msgs
    name: octomap_msgs
    rev: melodic-devel
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/octomap_msgs
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/octomap_tools.git
    name: octomap_tools
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/octomap_tools
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_octomap_server.git
    name: mrs_octomap_server
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_octomap_server
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_octomap_planner.git
    name: mrs_octomap_planner
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_octomap_planner
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/OctoMap/octomap_ros
    name: octomap_ros
    rev: melodic-devel
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/octomap_ros
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/subt_planning_lib.git
    name: subt_planning_lib
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/subt_planning_lib
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - repo: https://github.com/ctu-mrs/octomap_tools.git
    name: octomap_tools
    rev: c70046fad98e0f3571227fcf9533b3aa4951ae68
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/octomap_tools
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_octomap_server.git
    name: mrs_octomap_server
    rev: 1a3cdc6a481c9cdc584513d77bfab6620bde03d3
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_octomap_server
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_octomap_planner.git
    name: mrs_octomap_planner
    rev: df5693b09a91e43db5d0a688000f3c2eea4b007b
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_octomap_planner
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/OctoMap/octomap_ros
    name: octomap_ros
    rev: fb462a9e542dad60b6287b5e610c24b998bb65aa
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/octomap_ros
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/OctoMap/octomap_rviz_plugins
    name: octomap_rviz_plugins
    rev: 37b992585ed1cf7099c87c74f534253d3e7331e6
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/octomap_rviz_plugins
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/OctoMap/octomap_msgs
    name: octomap_msgs
    rev: dcaaf62bd071db0fcd806a98a9101a2e470f7f6d
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/octomap_msgs
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/OctoMap/octomap
    name: octomap
    rev: 92a9f14cafa5f567c47b58cbe91137c9a6ba1b0c
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/octomap
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/subt_planning_lib.git
    name: subt_planning_lib
    rev: e6536099c279e73401106dc160e974122fd8d95a
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/subt_planning_lib
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
