location: .gitman
sources:
  - repo: https://github.com/OctomMap/octomap
    name: octomap
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/octomap
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/OctoMap/octomap_rviz_plugins
    name: octomap_rviz_plugins
    rev: kinetic-devel
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/octomap_rviz_plugins
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/OctoMap/octomap_msgs
    name: octomap_msgs
    rev: melodic-devel
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/octomap_msgs
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/octomap_tools.git
    name: octomap_tools
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/octomap_tools
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_octomap_server.git
    name: mrs_octomap_server
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_octomap_server
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_octomap_planner.git
    name: mrs_octomap_planner
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_octomap_planner
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/OctoMap/octomap_ros
    name: octomap_ros
    rev: melodic-devel
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/octomap_ros
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - repo: https://github.com/ctu-mrs/octomap_tools.git
    name: octomap_tools
    rev: 2124d9d931597e55c20800ddd3a5f90fbfc6df09
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/octomap_tools
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_octomap_server.git
    name: mrs_octomap_server
    rev: d1dd7d847206c02ffd285431ef1ee3b5f959cce7
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_octomap_server
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_octomap_planner.git
    name: mrs_octomap_planner
    rev: aff36b37ea01a0331f1ec8f0e1ea4ae9d294795b
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_octomap_planner
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/OctoMap/octomap_ros
    name: octomap_ros
    rev: fb462a9e542dad60b6287b5e610c24b998bb65aa
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/octomap_ros
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/OctoMap/octomap_rviz_plugins
    name: octomap_rviz_plugins
    rev: c766489f62a96a4d37b3fa97d1aa867a0b81cf1c
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/octomap_rviz_plugins
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/OctoMap/octomap_msgs
    name: octomap_msgs
    rev: dcaaf62bd071db0fcd806a98a9101a2e470f7f6d
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/octomap_msgs
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/OctomMap/octomap
    name: octomap
    rev: 5f359052819cb7640af9d56282ff5c5050471443
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/octomap
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
